# Generated by Django 2.1.4 on 2018-12-28 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranshigen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generator',
            name='author',
        ),
    ]
