# Generated by Django 2.1.4 on 2018-12-28 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranshigen', '0002_remove_generator_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generator',
            name='created_date',
        ),
    ]
